version: '3.8'

services:
  discounts-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: discounts-db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - discounts-network
    volumes:
      - mssql_data:/var/opt/mssql/data

  discounts-api:
    image: discounts-api
    container_name: discounts-api
    build:
      context: ./Discounts
      dockerfile: Discounts.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DiscountsDb=Server=discounts-db;Database=DiscountsDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - discounts-db
    networks:
      - discounts-network

networks:
  discounts-network:
    driver: bridge

volumes:
  mssql_data:
